Feature/applayout
Sccr0123/Formula-1-Frenzy pull request #37
Opened 2022-03-20 20:14 UTC by wangheer2010

Changed the positioning of the view all buttons and dropdown button, putting them at the right end of the row. Increased the section titles' font size and the buttons' font size. Ready to merge.

2022-03-20 20:15 UTC, wangheer2010 commented
Sorry, please ignore this one! I will create another to merge to develop branch!

2022-03-21 00:10 UTC, moyangdev approved these changes

2022-03-22 01:48 UTC, Sccr0123 approved these changes

2022-03-22 01:48 UTC, Sccr0123 requested changes
Please do not push to main. Please only push to develop.

2022-03-22 04:38 UTC, Sccr0123 approved these changes

2022-03-22 04:38 UTC, closed without merging